/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  CircleLink,
  RectLink,
} from './components/mu-svg-screen';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface MuSvgScreen {
    /**
    * The height of the screen (for scaling)
    */
    'height': number;
    /**
    * Router history
    */
    'history': RouterHistory;
    /**
    * Array of links
    */
    'links': Array<JSX.Element|CircleLink|RectLink>;
    /**
    * The src of the background image
    */
    'src': string;
    /**
    * The width of the screen (for scaling)
    */
    'width': number;
  }
  interface MuSvgScreenAttributes extends StencilHTMLAttributes {
    /**
    * The height of the screen (for scaling)
    */
    'height': number;
    /**
    * Router history
    */
    'history'?: RouterHistory;
    /**
    * Array of links
    */
    'links'?: Array<JSX.Element|CircleLink|RectLink>;
    /**
    * The src of the background image
    */
    'src': string;
    /**
    * The width of the screen (for scaling)
    */
    'width': number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MuSvgScreen': Components.MuSvgScreen;
  }

  interface StencilIntrinsicElements {
    'mu-svg-screen': Components.MuSvgScreenAttributes;
  }


  interface HTMLMuSvgScreenElement extends Components.MuSvgScreen, HTMLStencilElement {}
  var HTMLMuSvgScreenElement: {
    prototype: HTMLMuSvgScreenElement;
    new (): HTMLMuSvgScreenElement;
  };

  interface HTMLElementTagNameMap {
    'mu-svg-screen': HTMLMuSvgScreenElement
  }

  interface ElementTagNameMap {
    'mu-svg-screen': HTMLMuSvgScreenElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
